/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

/**
 *
 * @author Gabriele
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelEntrar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sidedish = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 245, 216));
        setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, 40));

        jPanel1.setBackground(new java.awt.Color(217, 255, 245));

        LabelEntrar.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        LabelEntrar.setText("Entrar");

        jLabel3.setText("ENTRE PARA VISUALIZAR SUAS TAREFAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(LabelEntrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 450, 340));

        sidedish.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        sidedish.setText(" SIDE ");
        add(sidedish, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel2.setText(" DISH");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEntrar;
    private javax.swing.JButton jButtonLogar;
    private javax.swing.JButton jButtonLogar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Logo;
    private javax.swing.JLabel jLabel1Logo1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelCadastrar1;
    private javax.swing.JLabel jLabelMensagemUsuario;
    private javax.swing.JLabel jLabelMensagemUsuario1;
    private javax.swing.JLabel jLabelNomeEntrar;
    private javax.swing.JLabel jLabelNomeEntrar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFrente;
    private javax.swing.JPanel jPanelFrente1;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelFundo1;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JPasswordField jPasswordSenha1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel sidedish;
    // End of variables declaration//GEN-END:variables
}
